# Generated by Django 5.0.2 on 2024-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('iluminacion', models.BooleanField(default=False)),
                ('cubierta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_equipaciones', models.TextField()),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dorsal', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('puntos_local', models.PositiveIntegerField()),
                ('puntos_visitante', models.PositiveIntegerField()),
                ('observaciones', models.TextField()),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.deporte')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='gestion.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante', to='gestion.equipo')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.instalacion')),
            ],
        ),
    ]
