# Generated by Django 5.0.2 on 2024-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
